[package]
name = "scripts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12", features = ["full"] }  # Add tokio here
alloy = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-rlp = { workspace = true }
clap = "3.0"  # Assuming you are using clap for `Parser` derive macro
k256 = { workspace = true }

proto = { path = "../proto" }
executor = { path = "../executor" }

[lints]
workspace = true
