[package]
name = "clob-client"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
alloy = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
eyre = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }

# local deps
clob-core = { workspace = true }
clob-node = { workspace = true }
ivm-test-utils = { workspace = true }
clob-contracts = { workspace = true }
contracts = { workspace = true }
clob-test-utils = { workspace = true }