[book]
authors = ["infinityvm Core Contributors"]
language = "en"
multilingual = false
src = "book"
title = "infinityvm Book"

[output.html]
theme = "book/theme"
git-repository-url = "https://github.com/infinityvm/infinityvm"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"

# [preprocessor.template]
# before = ["links"]

# [preprocessor.index]

# [preprocessor.links]