[package]
name = "relayer"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tonic = { workspace = true }
tonic-reflection = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
alloy = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-rlp = { workspace = true }
clap = { workspace = true }
k256 = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
home = { workspace = true }
reth-db = { workspace = true }
reth-db-api = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }

proto = { path = "../proto" }
zkvm = { path = "../zkvm" }
crossbeam = "0.8"
