[package]
name = "clob-sp1"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
once_cell = { workspace = true }
bincode = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
sp1-build = { workspace = true }
sp1-sdk = { workspace = true }
bincode = { workspace = true } 