[package]
name = "executor"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tonic.workspace = true
prost.workspace = true
tokio.workspace = true
alloy.workspace = true
alloy-signer-local.workspace = true
alloy-sol-types.workspace = true
alloy-rlp.workspace = true
clap.workspace = true
k256.workspace = true
thiserror.workspace = true

proto = { path = "../proto" }
zkvm = { path = "../zkvm" }

[build-dependencies]
tonic-build.workspace = true