[package]
name = "coprocessor-node"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
# TODO: we should have "full" as a crate level feature. I think this will alloy us
# to remove the other alloy crate deps
alloy = { workspace = true, features = ["full", "reqwest"] }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
thiserror = { workspace = true }
home = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

proto = { path = "../proto" }
zkvm = { path = "../zkvm" }

[dev-dependencies]
alloy = { workspace = true, features = ["full", "reqwest", "node-bindings"] }
tracing-subscriber = "*"