[package]
name = "coprocessor-node"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
# TODO: we should have "full" as a crate level feature. I think this will alloy us
# to remove the other alloy crate deps
alloy = { workspace = true, features = ["reqwest"] }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
home = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
k256 = { workspace = true }
reth-db = { workspace = true }
tracing-subscriber = { workspace = true}
base64 = { workspace = true }
async-channel = { workspace = true }

db = { path = "../db" }
proto = { path = "../proto" }
zkvm = { path = "../zkvm" }
zkvm-executor = { path = "../zkvm-executor" }

[dev-dependencies]
alloy = { workspace = true, features = ["full", "reqwest", "node-bindings"] }
tracing-subscriber = "*"