[package]
name = "clob-programs"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
clob-core = { workspace = true }
borsh = { workspace = true }
alloy = { workspace = true, features = ["full", "contract", "transport-http", "transport-ws", "network", "providers", "pubsub", "signer-local", "signer-keystore", "rpc-types-debug", "rpc-types-trace", "json-rpc", "rpc-client", "rlp", "sol-types"] }
ivm-zkvm = { workspace = true }
ivm-abi = { workspace = true }
clob-test-utils = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
sp1-build = { workspace = true }
sp1-sdk = { workspace = true }
bincode = { workspace = true } 
ivm-sp1-utils = { workspace = true }
