[package]
name = "ivm-test-utils"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
alloy = { workspace = true, features = ["provider-anvil-node", "signer-local", "signers", "signer-keystore"] }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
alloy-signer-local = { version = "0.3.3", features = ["mnemonic"]}
alloy-signer = { version = "0.3.3" }

ivm-contracts = { workspace = true }
ivm-abi = { workspace = true }
