[package]
name = "ethos-reth"
version = "0.0.1"
edition = "2021"
rust-version = "1.79"
default-run = "ethos-reth"

[[bin]]
name = "ethos-reth"
path = "src/main.rs"

[dependencies]
alphanet-node = { git = "https://github.com/paradigmxyz/alphanet.git" }
reth = { git = "https://github.com/paradigmxyz/reth.git", rev = "v1.0.2", features = ["optimism"], default-features = false }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth.git", rev = "v1.0.2", default-features = false }
reth-node-optimism = { git = "https://github.com/paradigmxyz/reth.git", rev = "v1.0.2", default-features = false}

clap = { version = "4", features = ["derive"], default-features = false }
tracing = { version = "0.1.40" }
tikv-jemallocator = { version = "0.5", features = ["background_threads_runtime_support"], default-features = false }

[target.'cfg(not(windows))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[features]
default = [
  "jemalloc",
  "reth/optimism",
  "reth-node-optimism/optimism",
]

asm-keccak = ["reth/asm-keccak"]

jemalloc = ["dep:tikv-jemallocator"]
jemalloc-prof = ["jemalloc", "tikv-jemallocator?/profiling"]

min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]
