[package]
name = "intensity-test-sp1-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
sp1-zkvm = { version = "4", features = ["libm", "lib", "embedded"], default-features = false }
alloy = { version = "0.11", features = ["sol-types"], default-features = false }
borsh = { version = "1", features = ["derive", "std"], default-features = false }
sha2 = { version = "0.10", default-features = false }
