name: clob

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: ethos-artifacts
  REGION: us-west1
  GAR_LOCATION: us-docker.pkg.dev/ethos-artifacts/docker

jobs:
  docker-release:
    name: Docker release to Google Artifact Registry
    runs-on: ubicloud-standard-4

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          credentials_json: '${{ secrets.ARTIFACT_REGISTRY_CREDENTIALS }}'
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: '${{ secrets.ARTIFACT_REGISTRY_CREDENTIALS }}'

      - uses: technote-space/get-diff-action@v6.1.2
        id: diff
        with:
          PATTERNS: |
            .github/workflows/clob.yml
            clob/*
            Dockerfile.clob

      - name: Docker Metadata Pull
        id: meta
        if: env.GIT_DIFF
        uses: docker/metadata-action@v5
        with:
          images: |
            us-docker.pkg.dev/ethos-artifacts/docker/clob-node
          tags: |
            type=semver,pattern={{version}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
            type=ref,enable=true,priority=600,prefix=pr-,suffix=,event=pr
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

      - id: docker-push-clob
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        if: env.GIT_DIFF
        with:
          context: .
          file: Dockerfile.clob
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
